### PR TITLE
Added bpf_* types to binding.rs

### PR DESCRIPTION
**Pull request by uccidibuti**
I have rebuild bindings.rs adding some struct (i.e. bpf_map_info). I have also added a commented function "_create_binding" in build.rs, so it's possible rebuild binding.rs uncommenting "_create_binding" function.

### CODE REVIEW

**Comment by washley** [comment]
I would appreciate getting this merged. I just happened upon the missing bpf_map_info myself.

**Comment by uccidibuti** [comment]
In this moment to fix struct missing I'm using [rebpf-sys](https://github.com/uccidibuti/rebpf/tree/master/rebpf-sys) as libbpf Rust bindings for my library but I think that for Rust community is better have only one libbpf bindings package, so I would appreciate getting this merged and new version on crates.io.

**Comment by dansiemon** [comment]
I'll leave it to Alex to decide if he wants the build changes or not. The rebuild.sh script has the advantage of creating a clean build environment though the requirement for Docker may be hard on some users. I'm not sure that uncommenting lines in build.rs is right either. In the meantime I'll re-gen with the bpf functions exposed and do a separate PR for that.

**Comment by alexforster** [comment]
Ack, will try to take a look today.

**Comment by alexforster** [comment]
So, originally I was generating bindings in build.rs. I changed that [in this commit](https://github.com/alexforster/libbpf-sys/commit/9b66e3ff3410e3dd4b7b9f7d0907e66a2107ef30) to instead use the `rebuild.sh` script for two reasons: (1) it makes user's compile times much much faster, and (2) it means I don't have to worry about supporting every user's build environments.

**Comment by alexforster** [comment]
Thanks for catching these missing types! I think I'm going to go with #5 as the fix, only because I don't want to go back to using `build.rs` to generate bindings.

**Comment by alexforster** [comment]
Published `0.0.6-8` with the new `bpf_*` types

**Comment by uccidibuti** [comment]
Ok, thanks for new published version.. I'll remove rebpf-sys as first as possible..

**Pull request closed without merging**
